const data = [
  {
    id: 10001,
    firstname: "Abi",
    lastname: "",
    name: "Abi",
    afcWildCard1: "Los Angeles Chargers",
    afcWildCard2: "Buffalo Bills",
    afcWildCard3: "Cincinnati Bengals",
    nfcWildCard1: "San Francisco 49ers",
    nfcWildCard2: "Minnesota Vikings",
    nfcWildCard3: "Tampa Bay Buccaneers",
    afcDivisional1: "Kansas City Chiefs",
    afcDivisional2: "Cincinnati Bengals",
    nfcDivisional1: "Philadelphia Eagles",
    nfcDivisional2: "Minnesota Vikings",
    afcChampions: "Cincinnati Bengals",
    nfcChampions: "Philadelphia Eagles",
    superbowl: "Cincinnati Bengals",
    tiebreaker: 76,
  },
  {
    id: 10002,
    firstname: "Adi",
    lastname: "Nair",
    name: "Adi Nair",
    afcWildCard1: "Los Angeles Chargers",
    afcWildCard2: "Buffalo Bills",
    afcWildCard3: "Cincinnati Bengals",
    nfcWildCard1: "San Francisco 49ers",
    nfcWildCard2: "Minnesota Vikings",
    nfcWildCard3: "Tampa Bay Buccaneers",
    afcDivisional1: "Kansas City Chiefs",
    afcDivisional2: "Buffalo Bills",
    nfcDivisional1: "Philadelphia Eagles",
    nfcDivisional2: "San Francisco 49ers",
    afcChampions: "Buffalo Bills",
    nfcChampions: "San Francisco 49ers",
    superbowl: "Buffalo Bills",
    tiebreaker: 48,
  },
  {
    id: 10003,
    firstname: "Aishu",
    lastname: "",
    name: "Aishu",
    afcWildCard1: "Los Angeles Chargers",
    afcWildCard2: "Buffalo Bills",
    afcWildCard3: "Cincinnati Bengals",
    nfcWildCard1: "San Francisco 49ers",
    nfcWildCard2: "Minnesota Vikings",
    nfcWildCard3: "Dallas Cowboys",
    afcDivisional1: "Los Angeles Chargers",
    afcDivisional2: "Cincinnati Bengals",
    nfcDivisional1: "Philadelphia Eagles",
    nfcDivisional2: "Minnesota Vikings",
    afcChampions: "Cincinnati Bengals",
    nfcChampions: "Minnesota Vikings",
    superbowl: "Cincinnati Bengals",
    tiebreaker: 52,
  },
  {
    id: 10004,
    firstname: "Akhil",
    lastname: "A",
    name: "Akhil A",
    afcWildCard1: "Los Angeles Chargers",
    afcWildCard2: "Buffalo Bills",
    afcWildCard3: "Cincinnati Bengals",
    nfcWildCard1: "San Francisco 49ers",
    nfcWildCard2: "Minnesota Vikings",
    nfcWildCard3: "Tampa Bay Buccaneers",
    afcDivisional1: "Kansas City Chiefs",
    afcDivisional2: "Buffalo Bills",
    nfcDivisional1: "Philadelphia Eagles",
    nfcDivisional2: "San Francisco 49ers",
    afcChampions: "Kansas City Chiefs",
    nfcChampions: "San Francisco 49ers",
    superbowl: "San Francisco 49ers",
    tiebreaker: 57,
  },
  {
    id: 10005,
    firstname: "Akshay",
    lastname: "C",
    name: "Akshay C",
    afcWildCard1: "Los Angeles Chargers",
    afcWildCard2: "Buffalo Bills",
    afcWildCard3: "Cincinnati Bengals",
    nfcWildCard1: "San Francisco 49ers",
    nfcWildCard2: "New York Giants",
    nfcWildCard3: "Tampa Bay Buccaneers",
    afcDivisional1: "Kansas City Chiefs",
    afcDivisional2: "Buffalo Bills",
    nfcDivisional1: "Tampa Bay Buccaneers",
    nfcDivisional2: "San Francisco 49ers",
    afcChampions: "Buffalo Bills",
    nfcChampions: "Tampa Bay Buccaneers",
    superbowl: "Tampa Bay Buccaneers",
    tiebreaker: 41,
  },
  {
    id: 10006,
    firstname: "Akshay",
    lastname: "Brother",
    name: "Akshay Brother",
    afcWildCard1: "Jacksonville Jaguars",
    afcWildCard2: "Buffalo Bills",
    afcWildCard3: "Cincinnati Bengals",
    nfcWildCard1: "San Francisco 49ers",
    nfcWildCard2: "Minnesota Vikings",
    nfcWildCard3: "Tampa Bay Buccaneers",
    afcDivisional1: "Kansas City Chiefs",
    afcDivisional2: "Buffalo Bills",
    nfcDivisional1: "Philadelphia Eagles",
    nfcDivisional2: "Minnesota Vikings",
    afcChampions: "Buffalo Bills",
    nfcChampions: "Philadelphia Eagles",
    superbowl: "Buffalo Bills",
    tiebreaker: "48",
  },
  {
    id: 10007,
    firstname: "Alex",
    lastname: "Stein",
    name: "Alex Stein",
    afcWildCard1: "Los Angeles Chargers",
    afcWildCard2: "Buffalo Bills",
    afcWildCard3: "Cincinnati Bengals",
    nfcWildCard1: "San Francisco 49ers",
    nfcWildCard2: "Minnesota Vikings",
    nfcWildCard3: "Tampa Bay Buccaneers",
    afcDivisional1: "Los Angeles Chargers",
    afcDivisional2: "Buffalo Bills",
    nfcDivisional1: "Philadelphia Eagles",
    nfcDivisional2: "San Francisco 49ers",
    afcChampions: "Buffalo Bills",
    nfcChampions: "Philadelphia Eagles",
    superbowl: "Buffalo Bills",
    tiebreaker: 55,
  },
  {
    id: 10008,
    firstname: "Alex",
    lastname: "Zhen",
    name: "Alex Zhen",
    afcWildCard1: "Jacksonville Jaguars",
    afcWildCard2: "Buffalo Bills",
    afcWildCard3: "Cincinnati Bengals",
    nfcWildCard1: "San Francisco 49ers",
    nfcWildCard2: "Minnesota Vikings",
    nfcWildCard3: "Dallas Cowboys",
    afcDivisional1: "Kansas City Chiefs",
    afcDivisional2: "Buffalo Bills",
    nfcDivisional1: "Philadelphia Eagles",
    nfcDivisional2: "San Francisco 49ers",
    afcChampions: "Buffalo Bills",
    nfcChampions: "San Francisco 49ers",
    superbowl: "Buffalo Bills",
    tiebreaker: "N/A",
  },
  {
    id: 10009,
    firstname: "Alex",
    lastname: "C",
    name: "Alex C",
    afcWildCard1: "Jacksonville Jaguars",
    afcWildCard2: "Buffalo Bills",
    afcWildCard3: "Cincinnati Bengals",
    nfcWildCard1: "San Francisco 49ers",
    nfcWildCard2: "New York Giants",
    nfcWildCard3: "Tampa Bay Buccaneers",
    afcDivisional1: "Kansas City Chiefs",
    afcDivisional2: "Cincinnati Bengals",
    nfcDivisional1: "Philadelphia Eagles",
    nfcDivisional2: "San Francisco 49ers",
    afcChampions: "Kansas City Chiefs",
    nfcChampions: "San Francisco 49ers",
    superbowl: "Kansas City Chiefs",
    tiebreaker: 51,
  },
  {
    id: 10010,
    firstname: "Andrew",
    lastname: "Y",
    name: "Andrew Y",
    afcWildCard1: "Los Angeles Chargers",
    afcWildCard2: "Buffalo Bills",
    afcWildCard3: "Cincinnati Bengals",
    nfcWildCard1: "San Francisco 49ers",
    nfcWildCard2: "New York Giants",
    nfcWildCard3: "Dallas Cowboys",
    afcDivisional1: "Los Angeles Chargers",
    afcDivisional2: "Buffalo Bills",
    nfcDivisional1: "Philadelphia Eagles",
    nfcDivisional2: "San Francisco 49ers",
    afcChampions: "Buffalo Bills",
    nfcChampions: "San Francisco 49ers",
    superbowl: "Buffalo Bills",
    tiebreaker: 45,
  },
  {
    id: 10011,
    firstname: "Andrew",
    lastname: "Park",
    name: "Andrew Park",
    afcWildCard1: "Jacksonville Jaguars",
    afcWildCard2: "Buffalo Bills",
    afcWildCard3: "Cincinnati Bengals",
    nfcWildCard1: "San Francisco 49ers",
    nfcWildCard2: "New York Giants",
    nfcWildCard3: "Tampa Bay Buccaneers",
    afcDivisional1: "Kansas City Chiefs",
    afcDivisional2: "Buffalo Bills",
    nfcDivisional1: "Tampa Bay Buccaneers",
    nfcDivisional2: "San Francisco 49ers",
    afcChampions: "Kansas City Chiefs",
    nfcChampions: "San Francisco 49ers",
    superbowl: "San Francisco 49ers",
    tiebreaker: "N/A",
  },
  {
    id: 10012,
    firstname: "Arjun",
    lastname: "Sheelvanth",
    name: "Arjun Sheelvanth",
    afcWildCard1: "Los Angeles Chargers",
    afcWildCard2: "Buffalo Bills",
    afcWildCard3: "Cincinnati Bengals",
    nfcWildCard1: "San Francisco 49ers",
    nfcWildCard2: "Minnesota Vikings",
    nfcWildCard3: "Tampa Bay Buccaneers",
    afcDivisional1: "Kansas City Chiefs",
    afcDivisional2: "Buffalo Bills",
    nfcDivisional1: "Philadelphia Eagles",
    nfcDivisional2: "San Francisco 49ers",
    afcChampions: "Buffalo Bills",
    nfcChampions: "San Francisco 49ers",
    superbowl: "Buffalo Bills",
    tiebreaker: 59,
  },
  {
    id: 10013,
    firstname: "Arnav",
    lastname: "",
    name: "Arnav",
    afcWildCard1: "Jacksonville Jaguars",
    afcWildCard2: "Buffalo Bills",
    afcWildCard3: "Cincinnati Bengals",
    nfcWildCard1: "San Francisco 49ers",
    nfcWildCard2: "New York Giants",
    nfcWildCard3: "Tampa Bay Buccaneers",
    afcDivisional1: "Kansas City Chiefs",
    afcDivisional2: "Cincinnati Bengals",
    nfcDivisional1: "Philadelphia Eagles",
    nfcDivisional2: "San Francisco 49ers",
    afcChampions: "Cincinnati Bengals",
    nfcChampions: "San Francisco 49ers",
    superbowl: "San Francisco 49ers",
    tiebreaker: 45,
  },
  {
    id: 10014,
    firstname: "Aryan",
    lastname: "N",
    name: "Aryan N",
    afcWildCard1: "Jacksonville Jaguars",
    afcWildCard2: "Buffalo Bills",
    afcWildCard3: "Cincinnati Bengals",
    nfcWildCard1: "San Francisco 49ers",
    nfcWildCard2: "Minnesota Vikings",
    nfcWildCard3: "Dallas Cowboys",
    afcDivisional1: "Kansas City Chiefs",
    afcDivisional2: "Buffalo Bills",
    nfcDivisional1: "Philadelphia Eagles",
    nfcDivisional2: "San Francisco 49ers",
    afcChampions: "Kansas City Chiefs",
    nfcChampions: "Philadelphia Eagles",
    superbowl: "Kansas City Chiefs",
    tiebreaker: 45,
  },
  {
    id: 10015,
    firstname: "Chai",
    lastname: "Town",
    name: "Chai Town",
    afcWildCard1: "Jacksonville Jaguars",
    afcWildCard2: "Buffalo Bills",
    afcWildCard3: "Cincinnati Bengals",
    nfcWildCard1: "San Francisco 49ers",
    nfcWildCard2: "Minnesota Vikings",
    nfcWildCard3: "Tampa Bay Buccaneers",
    afcDivisional1: "Kansas City Chiefs",
    afcDivisional2: "Cincinnati Bengals",
    nfcDivisional1: "Philadelphia Eagles",
    nfcDivisional2: "San Francisco 49ers",
    afcChampions: "Cincinnati Bengals",
    nfcChampions: "San Francisco 49ers",
    superbowl: "Cincinnati Bengals",
    tiebreaker: 45,
  },
  {
    id: 10016,
    firstname: "Eshaan",
    lastname: "Bhattad",
    name: "Eshaan Bhattad",
    afcWildCard1: "Jacksonville Jaguars",
    afcWildCard2: "Buffalo Bills",
    afcWildCard3: "Cincinnati Bengals",
    nfcWildCard1: "San Francisco 49ers",
    nfcWildCard2: "New York Giants",
    nfcWildCard3: "Tampa Bay Buccaneers",
    afcDivisional1: "Kansas City Chiefs",
    afcDivisional2: "Buffalo Bills",
    nfcDivisional1: "Philadelphia Eagles",
    nfcDivisional2: "San Francisco 49ers",
    afcChampions: "Kansas City Chiefs",
    nfcChampions: "San Francisco 49ers",
    superbowl: "Kansas City Chiefs",
    tiebreaker: 40,
  },
  {
    id: 10017,
    firstname: "Govind",
    lastname: "S",
    name: "Govind S",
    afcWildCard1: "Los Angeles Chargers",
    afcWildCard2: "Buffalo Bills",
    afcWildCard3: "Cincinnati Bengals",
    nfcWildCard1: "San Francisco 49ers",
    nfcWildCard2: "Minnesota Vikings",
    nfcWildCard3: "Tampa Bay Buccaneers",
    afcDivisional1: "Los Angeles Chargers",
    afcDivisional2: "Buffalo Bills",
    nfcDivisional1: "Philadelphia Eagles",
    nfcDivisional2: "San Francisco 49ers",
    afcChampions: "Buffalo Bills",
    nfcChampions: "San Francisco 49ers",
    superbowl: "Buffalo Bills",
    tiebreaker: 58,
  },
  {
    id: 10018,
    firstname: "Ibby",
    lastname: "",
    name: "Ibby",
    afcWildCard1: "Jacksonville Jaguars",
    afcWildCard2: "Buffalo Bills",
    afcWildCard3: "Cincinnati Bengals",
    nfcWildCard1: "San Francisco 49ers",
    nfcWildCard2: "New York Giants",
    nfcWildCard3: "Tampa Bay Buccaneers",
    afcDivisional1: "Kansas City Chiefs",
    afcDivisional2: "Buffalo Bills",
    nfcDivisional1: "Philadelphia Eagles",
    nfcDivisional2: "San Francisco 49ers",
    afcChampions: "Buffalo Bills",
    nfcChampions: "Philadelphia Eagles",
    superbowl: "Buffalo Bills",
    tiebreaker: 50,
  },
  {
    id: 10019,
    firstname: "Jack",
    lastname: "L",
    name: "Jack L",
    afcWildCard1: "Jacksonville Jaguars",
    afcWildCard2: "Buffalo Bills",
    afcWildCard3: "Cincinnati Bengals",
    nfcWildCard1: "San Francisco 49ers",
    nfcWildCard2: "New York Giants",
    nfcWildCard3: "Dallas Cowboys",
    afcDivisional1: "Kansas City Chiefs",
    afcDivisional2: "Buffalo Bills",
    nfcDivisional1: "Philadelphia Eagles",
    nfcDivisional2: "San Francisco 49ers",
    afcChampions: "Buffalo Bills",
    nfcChampions: "Philadelphia Eagles",
    superbowl: "Philadelphia Eagles",
    tiebreaker: 50,
  },
  {
    id: 10020,
    firstname: "Jake",
    lastname: "TK",
    name: "Jake TK",
    afcWildCard1: "Los Angeles Chargers",
    afcWildCard2: "Buffalo Bills",
    afcWildCard3: "Cincinnati Bengals",
    nfcWildCard1: "San Francisco 49ers",
    nfcWildCard2: "Minnesota Vikings",
    nfcWildCard3: "Dallas Cowboys",
    afcDivisional1: "Kansas City Chiefs",
    afcDivisional2: "Cincinnati Bengals",
    nfcDivisional1: "Philadelphia Eagles",
    nfcDivisional2: "San Francisco 49ers",
    afcChampions: "Cincinnati Bengals",
    nfcChampions: "Philadelphia Eagles",
    superbowl: "Cincinnati Bengals",
    tiebreaker: 44,
  },
  {
    id: 10021,
    firstname: "Kavin",
    lastname: "",
    name: "Kavin",
    afcWildCard1: "Jacksonville Jaguars",
    afcWildCard2: "Buffalo Bills",
    afcWildCard3: "Cincinnati Bengals",
    nfcWildCard1: "San Francisco 49ers",
    nfcWildCard2: "Minnesota Vikings",
    nfcWildCard3: "Dallas Cowboys",
    afcDivisional1: "Kansas City Chiefs",
    afcDivisional2: "Buffalo Bills",
    nfcDivisional1: "Philadelphia Eagles",
    nfcDivisional2: "Minnesota Vikings",
    afcChampions: "Buffalo Bills",
    nfcChampions: "Philadelphia Eagles",
    superbowl: "Buffalo Bills",
    tiebreaker: 52,
  },
  {
    id: 10022,
    firstname: "Kayal",
    lastname: "",
    name: "Kayal",
    afcWildCard1: "Los Angeles Chargers",
    afcWildCard2: "Buffalo Bills",
    afcWildCard3: "Cincinnati Bengals",
    nfcWildCard1: "San Francisco 49ers",
    nfcWildCard2: "Minnesota Vikings",
    nfcWildCard3: "Tampa Bay Buccaneers",
    afcDivisional1: "Kansas City Chiefs",
    afcDivisional2: "Buffalo Bills",
    nfcDivisional1: "Tampa Bay Buccaneers",
    nfcDivisional2: "Minnesota Vikings",
    afcChampions: "Kansas City Chiefs",
    nfcChampions: "Tampa Bay Buccaneers",
    superbowl: "Kansas City Chiefs",
    tiebreaker: 58,
  },
  {
    id: 10023,
    firstname: "Kenneth",
    lastname: "Yang",
    name: "Kenneth Yang",
    afcWildCard1: "Los Angeles Chargers",
    afcWildCard2: "Buffalo Bills",
    afcWildCard3: "Cincinnati Bengals",
    nfcWildCard1: "San Francisco 49ers",
    nfcWildCard2: "New York Giants",
    nfcWildCard3: "Tampa Bay Buccaneers",
    afcDivisional1: "Kansas City Chiefs",
    afcDivisional2: "Buffalo Bills",
    nfcDivisional1: "New York Giants",
    nfcDivisional2: "San Francisco 49ers",
    afcChampions: "Buffalo Bills",
    nfcChampions: "San Francisco 49ers",
    superbowl: "San Francisco 49ers",
    tiebreaker: 58,
  },
  {
    id: 10024,
    firstname: "Khushi",
    lastname: "",
    name: "Khushi",
    afcWildCard1: "Los Angeles Chargers",
    afcWildCard2: "Buffalo Bills",
    afcWildCard3: "Cincinnati Bengals",
    nfcWildCard1: "San Francisco 49ers",
    nfcWildCard2: "Minnesota Vikings",
    nfcWildCard3: "Dallas Cowboys",
    afcDivisional1: "Kansas City Chiefs",
    afcDivisional2: "Buffalo Bills",
    nfcDivisional1: "Dallas Cowboys",
    nfcDivisional2: "San Francisco 49ers",
    afcChampions: "Buffalo Bills",
    nfcChampions: "San Francisco 49ers",
    superbowl: "Buffalo Bills",
    tiebreaker: 60,
  },
  {
    id: 10025,
    firstname: "Matt",
    lastname: "Y",
    name: "Matt Y",
    afcWildCard1: "Jacksonville Jaguars",
    afcWildCard2: "Buffalo Bills",
    afcWildCard3: "Cincinnati Bengals",
    nfcWildCard1: "San Francisco 49ers",
    nfcWildCard2: "New York Giants",
    nfcWildCard3: "Dallas Cowboys",
    afcDivisional1: "Kansas City Chiefs",
    afcDivisional2: "Buffalo Bills",
    nfcDivisional1: "Philadelphia Eagles",
    nfcDivisional2: "San Francisco 49ers",
    afcChampions: "Buffalo Bills",
    nfcChampions: "San Francisco 49ers",
    superbowl: "Buffalo Bills",
    tiebreaker: 41,
  },
  {
    id: 10026,
    firstname: "Matthew",
    lastname: "Tan",
    name: "Matthew Tan",
    afcWildCard1: "Los Angeles Chargers",
    afcWildCard2: "Buffalo Bills",
    afcWildCard3: "Cincinnati Bengals",
    nfcWildCard1: "San Francisco 49ers",
    nfcWildCard2: "Minnesota Vikings",
    nfcWildCard3: "Tampa Bay Buccaneers",
    afcDivisional1: "Kansas City Chiefs",
    afcDivisional2: "Cincinnati Bengals",
    nfcDivisional1: "Tampa Bay Buccaneers",
    nfcDivisional2: "San Francisco 49ers",
    afcChampions: "Kansas City Chiefs",
    nfcChampions: "San Francisco 49ers",
    superbowl: "Kansas City Chiefs",
    tiebreaker: 59,
  },
  {
    id: 10027,
    firstname: "Michael",
    lastname: "Treiber",
    name: "Michael Treiber",
    afcWildCard1: "Los Angeles Chargers",
    afcWildCard2: "Buffalo Bills",
    afcWildCard3: "Cincinnati Bengals",
    nfcWildCard1: "San Francisco 49ers",
    nfcWildCard2: "New York Giants",
    nfcWildCard3: "Tampa Bay Buccaneers",
    afcDivisional1: "Los Angeles Chargers",
    afcDivisional2: "Buffalo Bills",
    nfcDivisional1: "Philadelphia Eagles",
    nfcDivisional2: "San Francisco 49ers",
    afcChampions: "Buffalo Bills",
    nfcChampions: "San Francisco 49ers",
    superbowl: "Buffalo Bills",
    tiebreaker: 51,
  },
  {
    id: 10028,
    firstname: "Nate",
    lastname: "Tran",
    name: "Nate Tran",
    afcWildCard1: "Los Angeles Chargers",
    afcWildCard2: "Buffalo Bills",
    afcWildCard3: "Cincinnati Bengals",
    nfcWildCard1: "San Francisco 49ers",
    nfcWildCard2: "New York Giants",
    nfcWildCard3: "Dallas Cowboys",
    afcDivisional1: "Kansas City Chiefs",
    afcDivisional2: "Cincinnati Bengals",
    nfcDivisional1: "Philadelphia Eagles",
    nfcDivisional2: "San Francisco 49ers",
    afcChampions: "Cincinnati Bengals",
    nfcChampions: "Philadelphia Eagles",
    superbowl: "Philadelphia Eagles",
    tiebreaker: 69,
  },
  {
    id: 10029,
    firstname: "Nathan",
    lastname: "Sprovieri",
    name: "Nathan Sprovieri",
    afcWildCard1: "Los Angeles Chargers",
    afcWildCard2: "Buffalo Bills",
    afcWildCard3: "Cincinnati Bengals",
    nfcWildCard1: "Seattle Seahawks",
    nfcWildCard2: "Minnesota Vikings",
    nfcWildCard3: "Tampa Bay Buccaneers",
    afcDivisional1: "Kansas City Chiefs",
    afcDivisional2: "Buffalo Bills",
    nfcDivisional1: "Philadelphia Eagles",
    nfcDivisional2: "Tampa Bay Buccaneers",
    afcChampions: "Buffalo Bills",
    nfcChampions: "Tampa Bay Buccaneers",
    superbowl: "Buffalo Bills",
    tiebreaker: 58,
  },
  {
    id: 10030,
    firstname: "Neal",
    lastname: "Patel",
    name: "Neal Patel",
    afcWildCard1: "Los Angeles Chargers",
    afcWildCard2: "Buffalo Bills",
    afcWildCard3: "Cincinnati Bengals",
    nfcWildCard1: "San Francisco 49ers",
    nfcWildCard2: "Minnesota Vikings",
    nfcWildCard3: "Tampa Bay Buccaneers",
    afcDivisional1: "Kansas City Chiefs",
    afcDivisional2: "Buffalo Bills",
    nfcDivisional1: "Tampa Bay Buccaneers",
    nfcDivisional2: "San Francisco 49ers",
    afcChampions: "Buffalo Bills",
    nfcChampions: "San Francisco 49ers",
    superbowl: "Buffalo Bills",
    tiebreaker: 49,
  },
  {
    id: 10031,
    firstname: "Neha",
    lastname: "S",
    name: "Neha S",
    afcWildCard1: "Jacksonville Jaguars",
    afcWildCard2: "Buffalo Bills",
    afcWildCard3: "Cincinnati Bengals",
    nfcWildCard1: "San Francisco 49ers",
    nfcWildCard2: "Minnesota Vikings",
    nfcWildCard3: "Tampa Bay Buccaneers",
    afcDivisional1: "Kansas City Chiefs",
    afcDivisional2: "Buffalo Bills",
    nfcDivisional1: "Philadelphia Eagles",
    nfcDivisional2: "San Francisco 49ers",
    afcChampions: "Kansas City Chiefs",
    nfcChampions: "San Francisco 49ers",
    superbowl: "Kansas City Chiefs",
    tiebreaker: 41,
  },
  {
    id: 10032,
    firstname: "Nikhith",
    lastname: "R",
    name: "Nikhith R",
    afcWildCard1: "Jacksonville Jaguars",
    afcWildCard2: "Buffalo Bills",
    afcWildCard3: "Cincinnati Bengals",
    nfcWildCard1: "San Francisco 49ers",
    nfcWildCard2: "New York Giants",
    nfcWildCard3: "Dallas Cowboys",
    afcDivisional1: "Kansas City Chiefs",
    afcDivisional2: "Cincinnati Bengals",
    nfcDivisional1: "Philadelphia Eagles",
    nfcDivisional2: "San Francisco 49ers",
    afcChampions: "Kansas City Chiefs",
    nfcChampions: "San Francisco 49ers",
    superbowl: "Kansas City Chiefs",
    tiebreaker: 34,
  },
  {
    id: 10033,
    firstname: "Param",
    lastname: "M",
    name: "Param M",
    afcWildCard1: "Los Angeles Chargers",
    afcWildCard2: "Buffalo Bills",
    afcWildCard3: "Cincinnati Bengals",
    nfcWildCard1: "San Francisco 49ers",
    nfcWildCard2: "Minnesota Vikings",
    nfcWildCard3: "Tampa Bay Buccaneers",
    afcDivisional1: "Kansas City Chiefs",
    afcDivisional2: "Cincinnati Bengals",
    nfcDivisional1: "Tampa Bay Buccaneers",
    nfcDivisional2: "San Francisco 49ers",
    afcChampions: "Cincinnati Bengals",
    nfcChampions: "San Francisco 49ers",
    superbowl: "San Francisco 49ers",
    tiebreaker: 42,
  },
  {
    id: 10034,
    firstname: "Rahul",
    lastname: "Dhiman",
    name: "Rahul Dhiman",
    afcWildCard1: "Los Angeles Chargers",
    afcWildCard2: "Buffalo Bills",
    afcWildCard3: "Cincinnati Bengals",
    nfcWildCard1: "Seattle Seahawks",
    nfcWildCard2: "Minnesota Vikings",
    nfcWildCard3: "Tampa Bay Buccaneers",
    afcDivisional1: "Kansas City Chiefs",
    afcDivisional2: "Buffalo Bills",
    nfcDivisional1: "Philadelphia Eagles",
    nfcDivisional2: "Tampa Bay Buccaneers",
    afcChampions: "Buffalo Bills",
    nfcChampions: "Tampa Bay Buccaneers",
    superbowl: "Buffalo Bills",
    tiebreaker: "N/A",
  },
  {
    id: 10035,
    firstname: "Ricky",
    lastname: "Wang",
    name: "Ricky Wang",
    afcWildCard1: "Jacksonville Jaguars",
    afcWildCard2: "Buffalo Bills",
    afcWildCard3: "Cincinnati Bengals",
    nfcWildCard1: "San Francisco 49ers",
    nfcWildCard2: "Minnesota Vikings",
    nfcWildCard3: "Dallas Cowboys",
    afcDivisional1: "Kansas City Chiefs",
    afcDivisional2: "Buffalo Bills",
    nfcDivisional1: "Philadelphia Eagles",
    nfcDivisional2: "San Francisco 49ers",
    afcChampions: "Buffalo Bills",
    nfcChampions: "San Francisco 49ers",
    superbowl: "Buffalo Bills",
    tiebreaker: 37,
  },
  {
    id: 10036,
    firstname: "Rohan",
    lastname: "Ramani",
    name: "Rohan Ramani",
    afcWildCard1: "Jacksonville Jaguars",
    afcWildCard2: "Buffalo Bills",
    afcWildCard3: "Cincinnati Bengals",
    nfcWildCard1: "San Francisco 49ers",
    nfcWildCard2: "Minnesota Vikings",
    nfcWildCard3: "Dallas Cowboys",
    afcDivisional1: "Kansas City Chiefs",
    afcDivisional2: "Buffalo Bills",
    nfcDivisional1: "Philadelphia Eagles",
    nfcDivisional2: "San Francisco 49ers",
    afcChampions: "Buffalo Bills",
    nfcChampions: "San Francisco 49ers",
    superbowl: "Buffalo Bills",
    tiebreaker: 57,
  },
  {
    id: 10037,
    firstname: "Saksham",
    lastname: "Gupta",
    name: "Saksham Gupta",
    afcWildCard1: "Jacksonville Jaguars",
    afcWildCard2: "Buffalo Bills",
    afcWildCard3: "Cincinnati Bengals",
    nfcWildCard1: "San Francisco 49ers",
    nfcWildCard2: "Minnesota Vikings",
    nfcWildCard3: "Dallas Cowboys",
    afcDivisional1: "Kansas City Chiefs",
    afcDivisional2: "Buffalo Bills",
    nfcDivisional1: "Philadelphia Eagles",
    nfcDivisional2: "San Francisco 49ers",
    afcChampions: "Buffalo Bills",
    nfcChampions: "Philadelphia Eagles",
    superbowl: "Buffalo Bills",
    tiebreaker: 51,
  },
  {
    id: 10038,
    firstname: "Saneil",
    lastname: "",
    name: "Saneil",
    afcWildCard1: "Los Angeles Chargers",
    afcWildCard2: "Buffalo Bills",
    afcWildCard3: "Cincinnati Bengals",
    nfcWildCard1: "San Francisco 49ers",
    nfcWildCard2: "Minnesota Vikings",
    nfcWildCard3: "Dallas Cowboys",
    afcDivisional1: "Kansas City Chiefs",
    afcDivisional2: "Cincinnati Bengals",
    nfcDivisional1: "Dallas Cowboys",
    nfcDivisional2: "San Francisco 49ers",
    afcChampions: "Kansas City Chiefs",
    nfcChampions: "San Francisco 49ers",
    superbowl: "San Francisco 49ers",
    tiebreaker: 58,
  },
  {
    id: 10039,
    firstname: "Sarayu",
    lastname: "V",
    name: "Sarayu V",
    afcWildCard1: "Los Angeles Chargers",
    afcWildCard2: "Buffalo Bills",
    afcWildCard3: "Cincinnati Bengals",
    nfcWildCard1: "San Francisco 49ers",
    nfcWildCard2: "Minnesota Vikings",
    nfcWildCard3: "Tampa Bay Buccaneers",
    afcDivisional1: "Kansas City Chiefs",
    afcDivisional2: "Cincinnati Bengals",
    nfcDivisional1: "Philadelphia Eagles",
    nfcDivisional2: "San Francisco 49ers",
    afcChampions: "Cincinnati Bengals",
    nfcChampions: "San Francisco 49ers",
    superbowl: "Cincinnati Bengals",
    tiebreaker: "44",
  },
  {
    id: 10040,
    firstname: "Sathvik",
    lastname: "P",
    name: "Sathvik P",
    afcWildCard1: "Jacksonville Jaguars",
    afcWildCard2: "Buffalo Bills",
    afcWildCard3: "Cincinnati Bengals",
    nfcWildCard1: "Seattle Seahawks",
    nfcWildCard2: "Minnesota Vikings",
    nfcWildCard3: "Tampa Bay Buccaneers",
    afcDivisional1: "Kansas City Chiefs",
    afcDivisional2: "Buffalo Bills",
    nfcDivisional1: "Philadelphia Eagles",
    nfcDivisional2: "Minnesota Vikings",
    afcChampions: "",
    nfcChampions: "Minnesota Vikings",
    superbowl: "Minnesota Vikings",
    tiebreaker: 58,
  },
  {
    id: 10041,
    firstname: "Satvik",
    lastname: "",
    name: "Satvik",
    afcWildCard1: "Los Angeles Chargers",
    afcWildCard2: "Buffalo Bills",
    afcWildCard3: "Cincinnati Bengals",
    nfcWildCard1: "San Francisco 49ers",
    nfcWildCard2: "Minnesota Vikings",
    nfcWildCard3: "Tampa Bay Buccaneers",
    afcDivisional1: "Kansas City Chiefs",
    afcDivisional2: "Cincinnati Bengals",
    nfcDivisional1: "Philadelphia Eagles",
    nfcDivisional2: "San Francisco 49ers",
    afcChampions: "Cincinnati Bengals",
    nfcChampions: "Philadelphia Eagles",
    superbowl: "Philadelphia Eagles",
    tiebreaker: 75,
  },
  {
    id: 10042,
    firstname: "Sid",
    lastname: "Sharma",
    name: "Sid Sharma",
    afcWildCard1: "Los Angeles Chargers",
    afcWildCard2: "Buffalo Bills",
    afcWildCard3: "Cincinnati Bengals",
    nfcWildCard1: "San Francisco 49ers",
    nfcWildCard2: "Minnesota Vikings",
    nfcWildCard3: "Tampa Bay Buccaneers",
    afcDivisional1: "Kansas City Chiefs",
    afcDivisional2: "Buffalo Bills",
    nfcDivisional1: "Philadelphia Eagles",
    nfcDivisional2: "San Francisco 49ers",
    afcChampions: "Buffalo Bills",
    nfcChampions: "San Francisco 49ers",
    superbowl: "Buffalo Bills",
    tiebreaker: 51,
  },
  {
    id: 10043,
    firstname: "Sidd",
    lastname: "N",
    name: "Sidd N",
    afcWildCard1: "Los Angeles Chargers",
    afcWildCard2: "Buffalo Bills",
    afcWildCard3: "Cincinnati Bengals",
    nfcWildCard1: "San Francisco 49ers",
    nfcWildCard2: "New York Giants",
    nfcWildCard3: "Tampa Bay Buccaneers",
    afcDivisional1: "Kansas City Chiefs",
    afcDivisional2: "Buffalo Bills",
    nfcDivisional1: "Philadelphia Eagles",
    nfcDivisional2: "San Francisco 49ers",
    afcChampions: "Buffalo Bills",
    nfcChampions: "Philadelphia Eagles",
    superbowl: "Buffalo Bills",
    tiebreaker: 55,
  },
  {
    id: 10044,
    firstname: "Sri",
    lastname: "",
    name: "Sri",
    afcWildCard1: "Los Angeles Chargers",
    afcWildCard2: "Buffalo Bills",
    afcWildCard3: "Cincinnati Bengals",
    nfcWildCard1: "San Francisco 49ers",
    nfcWildCard2: "Minnesota Vikings",
    nfcWildCard3: "Tampa Bay Buccaneers",
    afcDivisional1: "Kansas City Chiefs",
    afcDivisional2: "Buffalo Bills",
    nfcDivisional1: "Philadelphia Eagles",
    nfcDivisional2: "Minnesota Vikings",
    afcChampions: "Kansas City Chiefs",
    nfcChampions: "Philadelphia Eagles",
    superbowl: "Philadelphia Eagles",
    tiebreaker: 73,
  },
  {
    id: 10045,
    firstname: "Tajes",
    lastname: "",
    name: "Tajes",
    afcWildCard1: "Jacksonville Jaguars",
    afcWildCard2: "Buffalo Bills",
    afcWildCard3: "Cincinnati Bengals",
    nfcWildCard1: "San Francisco 49ers",
    nfcWildCard2: "Minnesota Vikings",
    nfcWildCard3: "Dallas Cowboys",
    afcDivisional1: "Kansas City Chiefs",
    afcDivisional2: "Cincinnati Bengals",
    nfcDivisional1: "Philadelphia Eagles",
    nfcDivisional2: "San Francisco 49ers",
    afcChampions: "Kansas City Chiefs",
    nfcChampions: "San Francisco 49ers",
    superbowl: "Kansas City Chiefs",
    tiebreaker: 62,
  },
  {
    id: 10046,
    firstname: "Tim",
    lastname: "",
    name: "Tim",
    afcWildCard1: "Jacksonville Jaguars",
    afcWildCard2: "Buffalo Bills",
    afcWildCard3: "Cincinnati Bengals",
    nfcWildCard1: "San Francisco 49ers",
    nfcWildCard2: "Minnesota Vikings",
    nfcWildCard3: "Dallas Cowboys",
    afcDivisional1: "Kansas City Chiefs",
    afcDivisional2: "Buffalo Bills",
    nfcDivisional1: "Philadelphia Eagles",
    nfcDivisional2: "San Francisco 49ers",
    afcChampions: "Buffalo Bills",
    nfcChampions: "Philadelphia Eagles",
    superbowl: "Buffalo Bills",
    tiebreaker: 37,
  },
  {
    id: 10047,
    firstname: "Valki",
    lastname: "",
    name: "Valki",
    afcWildCard1: "Jacksonville Jaguars",
    afcWildCard2: "Buffalo Bills",
    afcWildCard3: "Cincinnati Bengals",
    nfcWildCard1: "San Francisco 49ers",
    nfcWildCard2: "New York Giants",
    nfcWildCard3: "Tampa Bay Buccaneers",
    afcDivisional1: "Kansas City Chiefs",
    afcDivisional2: "Cincinnati Bengals",
    nfcDivisional1: "Philadelphia Eagles",
    nfcDivisional2: "San Francisco 49ers",
    afcChampions: "Cincinnati Bengals",
    nfcChampions: "San Francisco 49ers",
    superbowl: "San Francisco 49ers",
    tiebreaker: "59",
  },
  {
    id: 10048,
    firstname: "Ved",
    lastname: "",
    name: "Ved",
    afcWildCard1: "Los Angeles Chargers",
    afcWildCard2: "Buffalo Bills",
    afcWildCard3: "Cincinnati Bengals",
    nfcWildCard1: "San Francisco 49ers",
    nfcWildCard2: "Minnesota Vikings",
    nfcWildCard3: "Tampa Bay Buccaneers",
    afcDivisional1: "Kansas City Chiefs",
    afcDivisional2: "Buffalo Bills",
    nfcDivisional1: "Philadelphia Eagles",
    nfcDivisional2: "San Francisco 49ers",
    afcChampions: "Buffalo Bills",
    nfcChampions: "San Francisco 49ers",
    superbowl: "Buffalo Bills",
    tiebreaker: 37,
  },
  {
    id: 10049,
    firstname: "Yunsik",
    lastname: "",
    name: "Yunsik",
    afcWildCard1: "Los Angeles Chargers",
    afcWildCard2: "Buffalo Bills",
    afcWildCard3: "Cincinnati Bengals",
    nfcWildCard1: "San Francisco 49ers",
    nfcWildCard2: "Minnesota Vikings",
    nfcWildCard3: "Dallas Cowboys",
    afcDivisional1: "Kansas City Chiefs",
    afcDivisional2: "Cincinnati Bengals",
    nfcDivisional1: "Philadelphia Eagles",
    nfcDivisional2: "San Francisco 49ers",
    afcChampions: "Cincinnati Bengals",
    nfcChampions: "Philadelphia Eagles",
    superbowl: "Cincinnati Bengals",
    tiebreaker: 48,
  },
  {
    id: 10050,
    firstname: "Andrew",
    lastname: "Lee",
    name: "Andrew Lee",
    afcWildCard1: "Jacksonville Jaguars",
    afcWildCard2: "Buffalo Bills",
    afcWildCard3: "Cincinnati Bengals",
    nfcWildCard1: "San Francisco 49ers",
    nfcWildCard2: "Minnesota Vikings",
    nfcWildCard3: "Tampa Bay Buccaneers",
    afcDivisional1: "Kansas City Chiefs",
    afcDivisional2: "Cincinnati Bengals",
    nfcDivisional1: "Philadelphia Eagles",
    nfcDivisional2: "San Francisco 49ers",
    afcChampions: "Kansas City Chiefs",
    nfcChampions: "Philadelphia Eagles",
    superbowl: "Kansas City Chiefs",
    tiebreaker: 62,
  },
  {
    id: 10051,
    firstname: "Rutvik",
    lastname: "",
    name: "Rutvik",
    afcWildCard1: "Los Angeles Chargers",
    afcWildCard2: "Buffalo Bills",
    afcWildCard3: "Cincinnati Bengals",
    nfcWildCard1: "San Francisco 49ers",
    nfcWildCard2: "New York Giants",
    nfcWildCard3: "Tampa Bay Buccaneers",
    afcDivisional1: "Kansas City Chiefs",
    afcDivisional2: "Buffalo Bills",
    nfcDivisional1: "Philadelphia Eagles",
    nfcDivisional2: "San Francisco 49ers",
    afcChampions: "Kansas City Chiefs",
    nfcChampions: "Philadelphia Eagles",
    superbowl: "Philadelphia Eagles",
    tiebreaker: 55,
  },
];

export default data;
