const data = [
  {
    'First Name': 'A',
    'Last Name': 'Choi',
    name: 'A Choi',
    id: 3866,
    afcWildCard1: 'Las Vegas Raiders',
    afcWildCard2: 'Buffalo Bills',
    afcWildCard3: 'Kansas City Chiefs',
    afcDivisional1: 'Tennessee Titans',
    afcDivisional2: 'Kansas City Chiefs',
    afcChampions: 'Kansas City Chiefs',
    nfcWildCard1: 'Tampa Bay Buccaneers',
    nfcWildCard2: 'Dallas Cowboys',
    nfcWildCard3: 'Los Angeles Rams',
    nfcDivisional1: 'Green Bay Packers',
    nfcDivisional2: 'Tampa Bay Buccaneers',
    nfcChampions: 'Green Bay Packers',
    superbowl: 'Green Bay Packers',
    tiebreaker: '49',
    points: 0,
  },
  {
    'First Name': 'Adi',
    'Last Name': 'Nair',
    name: 'Adi Nair',
    id: 7049,
    afcWildCard1: 'Cincinnati Bengals',
    afcWildCard2: 'Buffalo Bills',
    afcWildCard3: 'Kansas City Chiefs',
    afcDivisional1: 'Tennessee Titans',
    afcDivisional2: 'Buffalo Bills',
    afcChampions: 'Buffalo Bills',
    nfcWildCard1: 'Tampa Bay Buccaneers',
    nfcWildCard2: 'Dallas Cowboys',
    nfcWildCard3: 'Los Angeles Rams',
    nfcDivisional1: 'Green Bay Packers',
    nfcDivisional2: 'Dallas Cowboys',
    nfcChampions: 'Green Bay Packers',
    superbowl: 'Green Bay Packers',
    tiebreaker: '61',
    points: 0,
  },
  {
    'First Name': 'Aishu',
    'Last Name': 'V',
    name: 'Aishu V',
    id: 8462,
    afcWildCard1: 'Cincinnati Bengals',
    afcWildCard2: 'Buffalo Bills',
    afcWildCard3: 'Kansas City Chiefs',
    afcDivisional1: 'Cincinnati Bengals',
    afcDivisional2: 'Buffalo Bills',
    afcChampions: 'Buffalo Bills',
    nfcWildCard1: 'Tampa Bay Buccaneers',
    nfcWildCard2: 'Dallas Cowboys',
    nfcWildCard3: 'Los Angeles Rams',
    nfcDivisional1: 'Green Bay Packers',
    nfcDivisional2: 'Tampa Bay Buccaneers',
    nfcChampions: 'Green Bay Packers',
    superbowl: 'Green Bay Packers',
    tiebreaker: '',
    points: 0,
  },
  {
    'First Name': 'Alex',
    'Last Name': 'Stein',
    name: 'Alex Stein',
    id: 7528,
    afcWildCard1: 'Las Vegas Raiders',
    afcWildCard2: 'Buffalo Bills',
    afcWildCard3: 'Kansas City Chiefs',
    afcDivisional1: 'Tennessee Titans',
    afcDivisional2: 'Kansas City Chiefs',
    afcChampions: 'Kansas City Chiefs',
    nfcWildCard1: 'Tampa Bay Buccaneers',
    nfcWildCard2: 'Dallas Cowboys',
    nfcWildCard3: 'Los Angeles Rams',
    nfcDivisional1: 'Green Bay Packers',
    nfcDivisional2: 'Tampa Bay Buccaneers',
    nfcChampions: 'Green Bay Packers',
    superbowl: 'Green Bay Packers',
    tiebreaker: '48',
    points: 0,
  },
  {
    'First Name': 'Andrew',
    'Last Name': 'Yoon',
    name: 'Andrew Yoon',
    id: 1572,
    afcWildCard1: 'Cincinnati Bengals',
    afcWildCard2: 'Buffalo Bills',
    afcWildCard3: 'Kansas City Chiefs',
    afcDivisional1: 'Tennessee Titans',
    afcDivisional2: 'Buffalo Bills',
    afcChampions: 'Buffalo Bills',
    nfcWildCard1: 'Tampa Bay Buccaneers',
    nfcWildCard2: 'San Francisco 49ers',
    nfcWildCard3: 'Los Angeles Rams',
    nfcDivisional1: 'San Francisco 49ers',
    nfcDivisional2: 'Tampa Bay Buccaneers',
    nfcChampions: 'San Francisco 49ers',
    superbowl: 'Buffalo Bills',
    tiebreaker: '38',
    points: 0,
  },
  {
    'First Name': 'Ani',
    'Last Name': 'N',
    name: 'Ani N',
    id: 1239,
    afcWildCard1: 'Las Vegas Raiders',
    afcWildCard2: 'Buffalo Bills',
    afcWildCard3: 'Kansas City Chiefs',
    afcDivisional1: 'Tennessee Titans',
    afcDivisional2: 'Buffalo Bills',
    afcChampions: 'Buffalo Bills',
    nfcWildCard1: 'Tampa Bay Buccaneers',
    nfcWildCard2: 'San Francisco 49ers',
    nfcWildCard3: 'Los Angeles Rams',
    nfcDivisional1: 'Green Bay Packers',
    nfcDivisional2: 'Tampa Bay Buccaneers',
    nfcChampions: 'Green Bay Packers',
    superbowl: 'Buffalo Bills',
    tiebreaker: '59',
    points: 0,
  },
  {
    'First Name': 'AP',
    'Last Name': '',
    name: 'AP ',
    id: 4324,
    afcWildCard1: 'Cincinnati Bengals',
    afcWildCard2: 'Buffalo Bills',
    afcWildCard3: 'Kansas City Chiefs',
    afcDivisional1: 'Tennessee Titans',
    afcDivisional2: 'Buffalo Bills',
    afcChampions: 'Buffalo Bills',
    nfcWildCard1: 'Tampa Bay Buccaneers',
    nfcWildCard2: 'San Francisco 49ers',
    nfcWildCard3: 'Los Angeles Rams',
    nfcDivisional1: 'Green Bay Packers',
    nfcDivisional2: 'Los Angeles Rams',
    nfcChampions: 'Green Bay Packers',
    superbowl: 'Green Bay Packers',
    tiebreaker: '48',
    points: 0,
  },
  {
    'First Name': 'Aryan',
    'Last Name': 'N',
    name: 'Aryan N',
    id: 7377,
    afcWildCard1: 'Las Vegas Raiders',
    afcWildCard2: 'New England Patriots',
    afcWildCard3: 'Kansas City Chiefs',
    afcDivisional1: 'Tennessee Titans',
    afcDivisional2: 'Kansas City Chiefs',
    afcChampions: 'Tennessee Titans',
    nfcWildCard1: 'Tampa Bay Buccaneers',
    nfcWildCard2: 'San Francisco 49ers',
    nfcWildCard3: 'Los Angeles Rams',
    nfcDivisional1: 'Green Bay Packers',
    nfcDivisional2: 'Los Angeles Rams',
    nfcChampions: 'Green Bay Packers',
    superbowl: 'Tennessee Titans',
    tiebreaker: '59',
    points: 0,
  },
  {
    'First Name': 'Bella',
    'Last Name': 'S',
    name: 'Bella S',
    id: 9132,
    afcWildCard1: 'Cincinnati Bengals',
    afcWildCard2: 'Buffalo Bills',
    afcWildCard3: 'Kansas City Chiefs',
    afcDivisional1: 'Cincinnati Bengals',
    afcDivisional2: 'Kansas City Chiefs',
    afcChampions: 'Kansas City Chiefs',
    nfcWildCard1: 'Tampa Bay Buccaneers',
    nfcWildCard2: 'San Francisco 49ers',
    nfcWildCard3: 'Los Angeles Rams',
    nfcDivisional1: 'Green Bay Packers',
    nfcDivisional2: 'Los Angeles Rams',
    nfcChampions: 'Los Angeles Rams',
    superbowl: 'Los Angeles Rams',
    tiebreaker: '63',
    points: 0,
  },
  {
    'First Name': 'Ben ',
    'Last Name': 'L',
    name: 'Ben  L',
    id: 7993,
    afcWildCard1: 'Cincinnati Bengals',
    afcWildCard2: 'New England Patriots',
    afcWildCard3: 'Kansas City Chiefs',
    afcDivisional1: 'Tennessee Titans',
    afcDivisional2: 'Kansas City Chiefs',
    afcChampions: 'Tennessee Titans',
    nfcWildCard1: 'Tampa Bay Buccaneers',
    nfcWildCard2: 'San Francisco 49ers',
    nfcWildCard3: 'Los Angeles Rams',
    nfcDivisional1: 'Green Bay Packers',
    nfcDivisional2: 'Tampa Bay Buccaneers',
    nfcChampions: 'Green Bay Packers',
    superbowl: 'Green Bay Packers',
    tiebreaker: '63',
    points: 0,
  },
  {
    'First Name': 'Govind',
    'Last Name': 'S',
    name: 'Govind S',
    id: 1112,
    afcWildCard1: 'Cincinnati Bengals',
    afcWildCard2: 'Buffalo Bills',
    afcWildCard3: 'Kansas City Chiefs',
    afcDivisional1: 'Cincinnati Bengals',
    afcDivisional2: 'Kansas City Chiefs',
    afcChampions: 'Kansas City Chiefs',
    nfcWildCard1: 'Tampa Bay Buccaneers',
    nfcWildCard2: 'Dallas Cowboys',
    nfcWildCard3: 'Los Angeles Rams',
    nfcDivisional1: 'Green Bay Packers',
    nfcDivisional2: 'Tampa Bay Buccaneers',
    nfcChampions: 'Tampa Bay Buccaneers',
    superbowl: 'Kansas City Chiefs',
    tiebreaker: '54',
    points: 0,
  },
  {
    'First Name': 'Greg',
    'Last Name': 'Tow',
    name: 'Greg Tow',
    id: 7101,
    afcWildCard1: 'Cincinnati Bengals',
    afcWildCard2: 'Buffalo Bills',
    afcWildCard3: 'Kansas City Chiefs',
    afcDivisional1: 'Tennessee Titans',
    afcDivisional2: 'Buffalo Bills',
    afcChampions: 'Tennessee Titans',
    nfcWildCard1: 'Tampa Bay Buccaneers',
    nfcWildCard2: 'San Francisco 49ers',
    nfcWildCard3: 'Los Angeles Rams',
    nfcDivisional1: 'Los Angeles Rams',
    nfcDivisional2: 'Los Angeles Rams',
    nfcChampions: 'Los Angeles Rams',
    superbowl: 'Tennessee Titans',
    tiebreaker: '61',
    points: 0,
  },
  {
    'First Name': 'Hans',
    'Last Name': 'V',
    name: 'Hans V',
    id: 9908,
    afcWildCard1: 'Cincinnati Bengals',
    afcWildCard2: 'Buffalo Bills',
    afcWildCard3: 'Kansas City Chiefs',
    afcDivisional1: 'Tennessee Titans',
    afcDivisional2: 'Buffalo Bills',
    afcChampions: 'Buffalo Bills',
    nfcWildCard1: 'Philadelphia Eagles',
    nfcWildCard2: 'San Francisco 49ers',
    nfcWildCard3: 'Los Angeles Rams',
    nfcDivisional1: 'Green Bay Packers',
    nfcDivisional2: 'Los Angeles Rams',
    nfcChampions: 'Green Bay Packers',
    superbowl: 'Green Bay Packers',
    tiebreaker: '100',
    points: 0,
  },
  {
    'First Name': 'Harpy',
    'Last Name': '',
    name: 'Harpy ',
    id: 2176,
    afcWildCard1: 'Las Vegas Raiders',
    afcWildCard2: 'New England Patriots',
    afcWildCard3: 'Kansas City Chiefs',
    afcDivisional1: 'New England Patriots',
    afcDivisional2: 'Kansas City Chiefs',
    afcChampions: 'Kansas City Chiefs',
    nfcWildCard1: 'Tampa Bay Buccaneers',
    nfcWildCard2: 'Dallas Cowboys',
    nfcWildCard3: 'Los Angeles Rams',
    nfcDivisional1: 'Green Bay Packers',
    nfcDivisional2: 'Tampa Bay Buccaneers',
    nfcChampions: 'Tampa Bay Buccaneers',
    superbowl: 'Tampa Bay Buccaneers',
    tiebreaker: '46',
    points: 0,
  },
  {
    'First Name': 'Ibrahim',
    'Last Name': 'BHT',
    name: 'Ibrahim BHT',
    id: 7615,
    afcWildCard1: 'Cincinnati Bengals',
    afcWildCard2: 'New England Patriots',
    afcWildCard3: 'Kansas City Chiefs',
    afcDivisional1: 'Tennessee Titans',
    afcDivisional2: 'Kansas City Chiefs',
    afcChampions: 'Tennessee Titans',
    nfcWildCard1: 'Tampa Bay Buccaneers',
    nfcWildCard2: 'Dallas Cowboys',
    nfcWildCard3: 'Los Angeles Rams',
    nfcDivisional1: 'Green Bay Packers',
    nfcDivisional2: 'Tampa Bay Buccaneers',
    nfcChampions: 'Green Bay Packers',
    superbowl: 'Green Bay Packers',
    tiebreaker: '47',
    points: 0,
  },
  {
    'First Name': 'Jack ',
    'Last Name': 'Lamberti',
    name: 'Jack  Lamberti',
    id: 6627,
    afcWildCard1: 'Cincinnati Bengals',
    afcWildCard2: 'Buffalo Bills',
    afcWildCard3: 'Kansas City Chiefs',
    afcDivisional1: 'Cincinnati Bengals',
    afcDivisional2: 'Buffalo Bills',
    afcChampions: 'Buffalo Bills',
    nfcWildCard1: 'Tampa Bay Buccaneers',
    nfcWildCard2: 'San Francisco 49ers',
    nfcWildCard3: 'Los Angeles Rams',
    nfcDivisional1: 'Green Bay Packers',
    nfcDivisional2: 'Tampa Bay Buccaneers',
    nfcChampions: 'Green Bay Packers',
    superbowl: 'Green Bay Packers',
    tiebreaker: '52',
    points: 0,
  },
  {
    'First Name': 'Jake',
    'Last Name': 'Feldstein',
    name: 'Jake Feldstein',
    id: 6730,
    afcWildCard1: 'Cincinnati Bengals',
    afcWildCard2: 'Buffalo Bills',
    afcWildCard3: 'Kansas City Chiefs',
    afcDivisional1: 'Tennessee Titans',
    afcDivisional2: 'Kansas City Chiefs',
    afcChampions: 'Kansas City Chiefs',
    nfcWildCard1: 'Tampa Bay Buccaneers',
    nfcWildCard2: 'San Francisco 49ers',
    nfcWildCard3: 'Los Angeles Rams',
    nfcDivisional1: 'Green Bay Packers',
    nfcDivisional2: 'Los Angeles Rams',
    nfcChampions: 'Los Angeles Rams',
    superbowl: 'Kansas City Chiefs',
    tiebreaker: '71',
    points: 0,
  },
  {
    'First Name': 'Jonah',
    'Last Name': '',
    name: 'Jonah ',
    id: 9623,
    afcWildCard1: 'Cincinnati Bengals',
    afcWildCard2: 'Buffalo Bills',
    afcWildCard3: 'Kansas City Chiefs',
    afcDivisional1: 'Cincinnati Bengals',
    afcDivisional2: 'Kansas City Chiefs',
    afcChampions: 'Kansas City Chiefs',
    nfcWildCard1: 'Tampa Bay Buccaneers',
    nfcWildCard2: 'Dallas Cowboys',
    nfcWildCard3: 'Arizona Cardinals',
    nfcDivisional1: 'Green Bay Packers',
    nfcDivisional2: 'Tampa Bay Buccaneers',
    nfcChampions: 'Tampa Bay Buccaneers',
    superbowl: 'Kansas City Chiefs',
    tiebreaker: '53',
    points: 0,
  },
  {
    'First Name': 'Josh',
    'Last Name': 'S',
    name: 'Josh S',
    id: 6670,
    afcWildCard1: 'Cincinnati Bengals',
    afcWildCard2: 'Buffalo Bills',
    afcWildCard3: 'Kansas City Chiefs',
    afcDivisional1: 'Cincinnati Bengals',
    afcDivisional2: 'Kansas City Chiefs',
    afcChampions: 'Cincinnati Bengals',
    nfcWildCard1: 'Philadelphia Eagles',
    nfcWildCard2: 'Dallas Cowboys',
    nfcWildCard3: 'Los Angeles Rams',
    nfcDivisional1: 'Green Bay Packers',
    nfcDivisional2: 'Dallas Cowboys',
    nfcChampions: 'Dallas Cowboys',
    superbowl: 'Dallas Cowboys',
    tiebreaker: '48',
    points: 0,
  },
  {
    'First Name': 'Kaushik',
    'Last Name': 'P',
    name: 'Kaushik P',
    id: 2238,
    afcWildCard1: 'Las Vegas Raiders',
    afcWildCard2: 'Buffalo Bills',
    afcWildCard3: 'Kansas City Chiefs',
    afcDivisional1: 'Tennessee Titans',
    afcDivisional2: 'Buffalo Bills',
    afcChampions: 'Buffalo Bills',
    nfcWildCard1: 'Tampa Bay Buccaneers',
    nfcWildCard2: 'Dallas Cowboys',
    nfcWildCard3: 'Los Angeles Rams',
    nfcDivisional1: 'Green Bay Packers',
    nfcDivisional2: 'Tampa Bay Buccaneers',
    nfcChampions: 'Tampa Bay Buccaneers',
    superbowl: 'Buffalo Bills',
    tiebreaker: '58',
    points: 0,
  },
  {
    'First Name': 'Kenneth',
    'Last Name': 'Y',
    name: 'Kenneth Y',
    id: 7397,
    afcWildCard1: 'Cincinnati Bengals',
    afcWildCard2: 'Buffalo Bills',
    afcWildCard3: 'Kansas City Chiefs',
    afcDivisional1: 'Tennessee Titans',
    afcDivisional2: 'Kansas City Chiefs',
    afcChampions: 'Kansas City Chiefs',
    nfcWildCard1: 'Tampa Bay Buccaneers',
    nfcWildCard2: 'San Francisco 49ers',
    nfcWildCard3: 'Los Angeles Rams',
    nfcDivisional1: 'Green Bay Packers',
    nfcDivisional2: 'Tampa Bay Buccaneers',
    nfcChampions: 'Green Bay Packers',
    superbowl: 'Green Bay Packers',
    tiebreaker: '48',
    points: 0,
  },
  {
    'First Name': 'Kevin',
    'Last Name': 'H',
    name: 'Kevin H',
    id: 8784,
    afcWildCard1: 'Cincinnati Bengals',
    afcWildCard2: 'Buffalo Bills',
    afcWildCard3: 'Kansas City Chiefs',
    afcDivisional1: 'Cincinnati Bengals',
    afcDivisional2: 'Kansas City Chiefs',
    afcChampions: 'Kansas City Chiefs',
    nfcWildCard1: 'Tampa Bay Buccaneers',
    nfcWildCard2: 'San Francisco 49ers',
    nfcWildCard3: 'Los Angeles Rams',
    nfcDivisional1: 'Green Bay Packers',
    nfcDivisional2: 'Los Angeles Rams',
    nfcChampions: 'Green Bay Packers',
    superbowl: 'Green Bay Packers',
    tiebreaker: '59',
    points: 0,
  },
  {
    'First Name': 'Khushi',
    'Last Name': 'A',
    name: 'Khushi A',
    id: 3533,
    afcWildCard1: 'Las Vegas Raiders',
    afcWildCard2: 'New England Patriots',
    afcWildCard3: 'Kansas City Chiefs',
    afcDivisional1: 'New England Patriots',
    afcDivisional2: 'Kansas City Chiefs',
    afcChampions: 'Kansas City Chiefs',
    nfcWildCard1: 'Tampa Bay Buccaneers',
    nfcWildCard2: 'Dallas Cowboys',
    nfcWildCard3: 'Los Angeles Rams',
    nfcDivisional1: 'Green Bay Packers',
    nfcDivisional2: 'Dallas Cowboys',
    nfcChampions: 'Green Bay Packers',
    superbowl: 'Kansas City Chiefs',
    tiebreaker: '66',
    points: 0,
  },
  {
    'First Name': 'Nate',
    'Last Name': 'Tran',
    name: 'Nate Tran',
    id: 3728,
    afcWildCard1: 'Cincinnati Bengals',
    afcWildCard2: 'Buffalo Bills',
    afcWildCard3: 'Kansas City Chiefs',
    afcDivisional1: 'Cincinnati Bengals',
    afcDivisional2: 'Kansas City Chiefs',
    afcChampions: 'Kansas City Chiefs',
    nfcWildCard1: 'Tampa Bay Buccaneers',
    nfcWildCard2: 'San Francisco 49ers',
    nfcWildCard3: 'Los Angeles Rams',
    nfcDivisional1: 'Green Bay Packers',
    nfcDivisional2: 'Tampa Bay Buccaneers',
    nfcChampions: 'Green Bay Packers',
    superbowl: 'Kansas City Chiefs',
    tiebreaker: '54',
    points: 0,
  },
  {
    'First Name': 'Nathan ',
    'Last Name': 'S',
    name: 'Nathan  S',
    id: 9781,
    afcWildCard1: 'Las Vegas Raiders',
    afcWildCard2: 'Buffalo Bills',
    afcWildCard3: 'Pittsburgh Steelers',
    afcDivisional1: 'Tennessee Titans',
    afcDivisional2: 'Buffalo Bills',
    afcChampions: 'Buffalo Bills',
    nfcWildCard1: 'Tampa Bay Buccaneers',
    nfcWildCard2: 'Dallas Cowboys',
    nfcWildCard3: 'Arizona Cardinals',
    nfcDivisional1: 'Green Bay Packers',
    nfcDivisional2: 'Tampa Bay Buccaneers',
    nfcChampions: 'Green Bay Packers',
    superbowl: 'Green Bay Packers',
    tiebreaker: '0',
    points: 0,
  },
  {
    'First Name': 'Neal',
    'Last Name': 'Patel',
    name: 'Neal Patel',
    id: 7155,
    afcWildCard1: 'Las Vegas Raiders',
    afcWildCard2: 'Buffalo Bills',
    afcWildCard3: 'Kansas City Chiefs',
    afcDivisional1: 'Tennessee Titans',
    afcDivisional2: 'Buffalo Bills',
    afcChampions: 'Buffalo Bills',
    nfcWildCard1: 'Tampa Bay Buccaneers',
    nfcWildCard2: 'San Francisco 49ers',
    nfcWildCard3: 'Los Angeles Rams',
    nfcDivisional1: 'Green Bay Packers',
    nfcDivisional2: 'Los Angeles Rams',
    nfcChampions: 'Los Angeles Rams',
    superbowl: 'Buffalo Bills',
    tiebreaker: '43',
    points: 0,
  },
  {
    'First Name': 'Nikhith',
    'Last Name': 'R',
    name: 'Nikhith R',
    id: 2309,
    afcWildCard1: 'Cincinnati Bengals',
    afcWildCard2: 'New England Patriots',
    afcWildCard3: 'Kansas City Chiefs',
    afcDivisional1: 'Tennessee Titans',
    afcDivisional2: 'Kansas City Chiefs',
    afcChampions: 'Kansas City Chiefs',
    nfcWildCard1: 'Tampa Bay Buccaneers',
    nfcWildCard2: 'San Francisco 49ers',
    nfcWildCard3: 'Los Angeles Rams',
    nfcDivisional1: 'Green Bay Packers',
    nfcDivisional2: 'Los Angeles Rams',
    nfcChampions: 'Green Bay Packers',
    superbowl: 'Green Bay Packers',
    tiebreaker: '51',
    points: 0,
  },
  {
    'First Name': 'Noah',
    'Last Name': 'P',
    name: 'Noah P',
    id: 5343,
    afcWildCard1: 'Cincinnati Bengals',
    afcWildCard2: 'New England Patriots',
    afcWildCard3: 'Kansas City Chiefs',
    afcDivisional1: 'Tennessee Titans',
    afcDivisional2: 'Kansas City Chiefs',
    afcChampions: 'Kansas City Chiefs',
    nfcWildCard1: 'Tampa Bay Buccaneers',
    nfcWildCard2: 'Dallas Cowboys',
    nfcWildCard3: 'Los Angeles Rams',
    nfcDivisional1: 'Green Bay Packers',
    nfcDivisional2: 'Los Angeles Rams',
    nfcChampions: 'Los Angeles Rams',
    superbowl: 'Tennessee Titans',
    tiebreaker: '58',
    points: 0,
  },
  {
    'First Name': 'Noah',
    'Last Name': 'S',
    name: 'Noah S',
    id: 9457,
    afcWildCard1: 'Las Vegas Raiders',
    afcWildCard2: 'Buffalo Bills',
    afcWildCard3: 'Pittsburgh Steelers',
    afcDivisional1: 'Tennessee Titans',
    afcDivisional2: 'Buffalo Bills',
    afcChampions: 'Tennessee Titans',
    nfcWildCard1: 'Philadelphia Eagles',
    nfcWildCard2: 'Dallas Cowboys',
    nfcWildCard3: 'Los Angeles Rams',
    nfcDivisional1: 'Philadelphia Eagles',
    nfcDivisional2: 'Los Angeles Rams',
    nfcChampions: 'Los Angeles Rams',
    superbowl: 'Tennessee Titans',
    tiebreaker: '0',
    points: 0,
  },
  {
    'First Name': 'Rahul ',
    'Last Name': 'D',
    name: 'Rahul  D',
    id: 9030,
    afcWildCard1: 'Cincinnati Bengals',
    afcWildCard2: 'New England Patriots',
    afcWildCard3: 'Kansas City Chiefs',
    afcDivisional1: 'New England Patriots',
    afcDivisional2: 'Kansas City Chiefs',
    afcChampions: 'Kansas City Chiefs',
    nfcWildCard1: 'Tampa Bay Buccaneers',
    nfcWildCard2: 'Dallas Cowboys',
    nfcWildCard3: 'Los Angeles Rams',
    nfcDivisional1: 'Los Angeles Rams',
    nfcDivisional2: 'Tampa Bay Buccaneers',
    nfcChampions: 'Los Angeles Rams',
    superbowl: 'Los Angeles Rams',
    tiebreaker: '56',
    points: 0,
  },
  {
    'First Name': 'Ricky',
    'Last Name': '',
    name: 'Ricky ',
    id: 9786,
    afcWildCard1: 'Cincinnati Bengals',
    afcWildCard2: 'Buffalo Bills',
    afcWildCard3: 'Kansas City Chiefs',
    afcDivisional1: 'Cincinnati Bengals',
    afcDivisional2: 'Buffalo Bills',
    afcChampions: 'Buffalo Bills',
    nfcWildCard1: 'Tampa Bay Buccaneers',
    nfcWildCard2: 'San Francisco 49ers',
    nfcWildCard3: 'Los Angeles Rams',
    nfcDivisional1: 'Green Bay Packers',
    nfcDivisional2: 'Los Angeles Rams',
    nfcChampions: 'Green Bay Packers',
    superbowl: 'Green Bay Packers',
    tiebreaker: '51',
    points: 0,
  },
  {
    'First Name': 'Rishi',
    'Last Name': 'K',
    name: 'Rishi K',
    id: 4868,
    afcWildCard1: 'Cincinnati Bengals',
    afcWildCard2: 'Buffalo Bills',
    afcWildCard3: 'Kansas City Chiefs',
    afcDivisional1: 'Tennessee Titans',
    afcDivisional2: 'Buffalo Bills',
    afcChampions: 'Tennessee Titans',
    nfcWildCard1: 'Tampa Bay Buccaneers',
    nfcWildCard2: 'Dallas Cowboys',
    nfcWildCard3: 'Los Angeles Rams',
    nfcDivisional1: 'Green Bay Packers',
    nfcDivisional2: 'Dallas Cowboys',
    nfcChampions: 'Green Bay Packers',
    superbowl: 'Green Bay Packers',
    tiebreaker: '40',
    points: 0,
  },
  {
    'First Name': 'Rohan',
    'Last Name': 'P',
    name: 'Rohan P',
    id: 5468,
    afcWildCard1: 'Cincinnati Bengals',
    afcWildCard2: 'Buffalo Bills',
    afcWildCard3: 'Kansas City Chiefs',
    afcDivisional1: 'Cincinnati Bengals',
    afcDivisional2: 'Kansas City Chiefs',
    afcChampions: 'Kansas City Chiefs',
    nfcWildCard1: 'Tampa Bay Buccaneers',
    nfcWildCard2: 'San Francisco 49ers',
    nfcWildCard3: 'Los Angeles Rams',
    nfcDivisional1: 'San Francisco 49ers',
    nfcDivisional2: 'Tampa Bay Buccaneers',
    nfcChampions: 'Tampa Bay Buccaneers',
    superbowl: 'Tampa Bay Buccaneers',
    tiebreaker: '54',
    points: 0,
  },
  {
    'First Name': 'Rutvik',
    'Last Name': '',
    name: 'Rutvik ',
    id: 9881,
    afcWildCard1: 'Cincinnati Bengals',
    afcWildCard2: 'New England Patriots',
    afcWildCard3: 'Kansas City Chiefs',
    afcDivisional1: 'Tennessee Titans',
    afcDivisional2: 'Kansas City Chiefs',
    afcChampions: 'Tennessee Titans',
    nfcWildCard1: 'Philadelphia Eagles',
    nfcWildCard2: 'Dallas Cowboys',
    nfcWildCard3: 'Los Angeles Rams',
    nfcDivisional1: 'Green Bay Packers',
    nfcDivisional2: 'Dallas Cowboys',
    nfcChampions: 'Green Bay Packers',
    superbowl: 'Green Bay Packers',
    tiebreaker: '47',
    points: 0,
  },
  {
    'First Name': 'Ryan',
    'Last Name': 'S',
    name: 'Ryan S',
    id: 7477,
    afcWildCard1: 'Cincinnati Bengals',
    afcWildCard2: 'Buffalo Bills',
    afcWildCard3: 'Kansas City Chiefs',
    afcDivisional1: 'Cincinnati Bengals',
    afcDivisional2: 'Kansas City Chiefs',
    afcChampions: 'Kansas City Chiefs',
    nfcWildCard1: 'Tampa Bay Buccaneers',
    nfcWildCard2: 'San Francisco 49ers',
    nfcWildCard3: 'Los Angeles Rams',
    nfcDivisional1: 'Green Bay Packers',
    nfcDivisional2: 'Tampa Bay Buccaneers',
    nfcChampions: 'Green Bay Packers',
    superbowl: 'Kansas City Chiefs',
    tiebreaker: '53',
    points: 0,
  },
  {
    'First Name': 'Saksham',
    'Last Name': '',
    name: 'Saksham ',
    id: 1399,
    afcWildCard1: 'Las Vegas Raiders',
    afcWildCard2: 'Buffalo Bills',
    afcWildCard3: 'Kansas City Chiefs',
    afcDivisional1: 'Las Vegas Raiders',
    afcDivisional2: 'Kansas City Chiefs',
    afcChampions: 'Kansas City Chiefs',
    nfcWildCard1: 'Philadelphia Eagles',
    nfcWildCard2: 'Dallas Cowboys',
    nfcWildCard3: 'Los Angeles Rams',
    nfcDivisional1: 'Green Bay Packers',
    nfcDivisional2: 'Los Angeles Rams',
    nfcChampions: 'Green Bay Packers',
    superbowl: 'Kansas City Chiefs',
    tiebreaker: '50',
    points: 0,
  },
  {
    'First Name': 'Satvik',
    'Last Name': '',
    name: 'Satvik ',
    id: 9309,
    afcWildCard1: 'Cincinnati Bengals',
    afcWildCard2: 'Buffalo Bills',
    afcWildCard3: 'Kansas City Chiefs',
    afcDivisional1: 'Tennessee Titans',
    afcDivisional2: 'Buffalo Bills',
    afcChampions: 'Tennessee Titans',
    nfcWildCard1: 'Tampa Bay Buccaneers',
    nfcWildCard2: 'San Francisco 49ers',
    nfcWildCard3: 'Los Angeles Rams',
    nfcDivisional1: 'Green Bay Packers',
    nfcDivisional2: 'Los Angeles Rams',
    nfcChampions: 'Green Bay Packers',
    superbowl: 'Green Bay Packers',
    tiebreaker: '57',
    points: 0,
  },
  {
    'First Name': 'Sidd',
    'Last Name': 'N',
    name: 'Sidd N',
    id: 2511,
    afcWildCard1: 'Cincinnati Bengals',
    afcWildCard2: 'Buffalo Bills',
    afcWildCard3: 'Kansas City Chiefs',
    afcDivisional1: 'Tennessee Titans',
    afcDivisional2: 'Kansas City Chiefs',
    afcChampions: 'Kansas City Chiefs',
    nfcWildCard1: 'Tampa Bay Buccaneers',
    nfcWildCard2: 'Dallas Cowboys',
    nfcWildCard3: 'Los Angeles Rams',
    nfcDivisional1: 'Green Bay Packers',
    nfcDivisional2: 'Tampa Bay Buccaneers',
    nfcChampions: 'Green Bay Packers',
    superbowl: 'Green Bay Packers',
    tiebreaker: '50',
    points: 0,
  },
  {
    'First Name': 'Siddharth',
    'Last Name': 'Sharma',
    name: 'Siddharth Sharma',
    id: 7443,
    afcWildCard1: 'Cincinnati Bengals',
    afcWildCard2: 'New England Patriots',
    afcWildCard3: 'Kansas City Chiefs',
    afcDivisional1: 'Cincinnati Bengals',
    afcDivisional2: 'New England Patriots',
    afcChampions: 'Cincinnati Bengals',
    nfcWildCard1: 'Tampa Bay Buccaneers',
    nfcWildCard2: 'San Francisco 49ers',
    nfcWildCard3: 'Los Angeles Rams',
    nfcDivisional1: 'Green Bay Packers',
    nfcDivisional2: 'Los Angeles Rams',
    nfcChampions: 'Los Angeles Rams',
    superbowl: 'Cincinnati Bengals',
    tiebreaker: '44',
    points: 0,
  },
  {
    'First Name': 'Sri',
    'Last Name': 'M',
    name: 'Sri M',
    id: 2047,
    afcWildCard1: 'Cincinnati Bengals',
    afcWildCard2: 'Buffalo Bills',
    afcWildCard3: 'Kansas City Chiefs',
    afcDivisional1: 'Cincinnati Bengals',
    afcDivisional2: 'Buffalo Bills',
    afcChampions: 'Cincinnati Bengals',
    nfcWildCard1: 'Tampa Bay Buccaneers',
    nfcWildCard2: 'Dallas Cowboys',
    nfcWildCard3: 'Arizona Cardinals',
    nfcDivisional1: 'Green Bay Packers',
    nfcDivisional2: 'Dallas Cowboys',
    nfcChampions: 'Green Bay Packers',
    superbowl: 'Green Bay Packers',
    tiebreaker: '38',
    points: 0,
  },
  {
    'First Name': 'Srihas',
    'Last Name': 'R',
    name: 'Srihas R',
    id: 6452,
    afcWildCard1: 'Las Vegas Raiders',
    afcWildCard2: 'Buffalo Bills',
    afcWildCard3: 'Kansas City Chiefs',
    afcDivisional1: 'Tennessee Titans',
    afcDivisional2: 'Kansas City Chiefs',
    afcChampions: 'Kansas City Chiefs',
    nfcWildCard1: 'Tampa Bay Buccaneers',
    nfcWildCard2: 'San Francisco 49ers',
    nfcWildCard3: 'Los Angeles Rams',
    nfcDivisional1: 'Green Bay Packers',
    nfcDivisional2: 'Tampa Bay Buccaneers',
    nfcChampions: 'Green Bay Packers',
    superbowl: 'Green Bay Packers',
    tiebreaker: '55',
    points: 0,
  },
  {
    'First Name': 'Stephen',
    'Last Name': 'A',
    name: 'Stephen A',
    id: 7977,
    afcWildCard1: 'Las Vegas Raiders',
    afcWildCard2: 'New England Patriots',
    afcWildCard3: 'Kansas City Chiefs',
    afcDivisional1: 'New England Patriots',
    afcDivisional2: 'Kansas City Chiefs',
    afcChampions: 'Kansas City Chiefs',
    nfcWildCard1: 'Tampa Bay Buccaneers',
    nfcWildCard2: 'Dallas Cowboys',
    nfcWildCard3: 'Los Angeles Rams',
    nfcDivisional1: 'Green Bay Packers',
    nfcDivisional2: 'Dallas Cowboys',
    nfcChampions: 'Green Bay Packers',
    superbowl: 'Green Bay Packers',
    tiebreaker: '51',
    points: 0,
  },
  {
    'First Name': 'Sunny',
    'Last Name': '',
    name: 'Sunny ',
    id: 5419,
    afcWildCard1: 'Cincinnati Bengals',
    afcWildCard2: 'New England Patriots',
    afcWildCard3: 'Kansas City Chiefs',
    afcDivisional1: 'Tennessee Titans',
    afcDivisional2: 'Kansas City Chiefs',
    afcChampions: 'Kansas City Chiefs',
    nfcWildCard1: 'Tampa Bay Buccaneers',
    nfcWildCard2: 'Dallas Cowboys',
    nfcWildCard3: 'Arizona Cardinals',
    nfcDivisional1: 'Green Bay Packers',
    nfcDivisional2: 'Dallas Cowboys',
    nfcChampions: 'Green Bay Packers',
    superbowl: 'Green Bay Packers',
    tiebreaker: '54',
    points: 0,
  },
  {
    'First Name': 'Teja',
    'Last Name': '',
    name: 'Teja ',
    id: 8078,
    afcWildCard1: 'Cincinnati Bengals',
    afcWildCard2: 'Buffalo Bills',
    afcWildCard3: 'Kansas City Chiefs',
    afcDivisional1: 'Cincinnati Bengals',
    afcDivisional2: 'Kansas City Chiefs',
    afcChampions: 'Kansas City Chiefs',
    nfcWildCard1: 'Tampa Bay Buccaneers',
    nfcWildCard2: 'San Francisco 49ers',
    nfcWildCard3: 'Los Angeles Rams',
    nfcDivisional1: 'Green Bay Packers',
    nfcDivisional2: 'Tampa Bay Buccaneers',
    nfcChampions: 'Green Bay Packers',
    superbowl: 'Green Bay Packers',
    tiebreaker: '55',
    points: 0,
  },
  {
    'First Name': 'Aaron',
    'Last Name': 'Wang',
    name: 'Aaron Wang',
    id: 2787,
    afcWildCard1: 'Cincinnati Bengals',
    afcWildCard2: 'New England Patriots',
    afcWildCard3: 'Kansas City Chiefs',
    afcDivisional1: 'New England Patriots',
    afcDivisional2: 'Kansas City Chiefs',
    afcChampions: 'Kansas City Chiefs',
    nfcWildCard1: 'Tampa Bay Buccaneers',
    nfcWildCard2: 'San Francisco 49ers',
    nfcWildCard3: 'Los Angeles Rams',
    nfcDivisional1: 'Green Bay Packers',
    nfcDivisional2: 'Tampa Bay Buccaneers',
    nfcChampions: 'Green Bay Packers',
    superbowl: 'Kansas City Chiefs',
    tiebreaker: '47',
    points: 0,
  },
  {
    'First Name': 'Tim ',
    'Last Name': 'Yoon',
    name: 'Tim  Yoon',
    id: 8151,
    afcWildCard1: 'Cincinnati Bengals',
    afcWildCard2: 'Buffalo Bills',
    afcWildCard3: 'Kansas City Chiefs',
    afcDivisional1: 'Cincinnati Bengals',
    afcDivisional2: 'Kansas City Chiefs',
    afcChampions: 'Kansas City Chiefs',
    nfcWildCard1: 'Tampa Bay Buccaneers',
    nfcWildCard2: 'San Francisco 49ers',
    nfcWildCard3: 'Los Angeles Rams',
    nfcDivisional1: 'Green Bay Packers',
    nfcDivisional2: 'Los Angeles Rams',
    nfcChampions: 'Green Bay Packers',
    superbowl: 'Green Bay Packers',
    tiebreaker: '44',
    points: 0,
  },
  {
    'First Name': 'Varun',
    'Last Name': 'M',
    name: 'Varun M',
    id: 9144,
    afcWildCard1: 'Las Vegas Raiders',
    afcWildCard2: 'Buffalo Bills',
    afcWildCard3: 'Kansas City Chiefs',
    afcDivisional1: 'Tennessee Titans',
    afcDivisional2: 'Kansas City Chiefs',
    afcChampions: 'Kansas City Chiefs',
    nfcWildCard1: 'Tampa Bay Buccaneers',
    nfcWildCard2: 'Dallas Cowboys',
    nfcWildCard3: 'Los Angeles Rams',
    nfcDivisional1: 'Green Bay Packers',
    nfcDivisional2: 'Tampa Bay Buccaneers',
    nfcChampions: 'Tampa Bay Buccaneers',
    superbowl: 'Tampa Bay Buccaneers',
    tiebreaker: '61',
    points: 0,
  },
  {
    'First Name': 'Vasin ',
    'Last Name': 'J',
    name: 'Vasin  J',
    id: 1742,
    afcWildCard1: 'Cincinnati Bengals',
    afcWildCard2: 'Buffalo Bills',
    afcWildCard3: 'Kansas City Chiefs',
    afcDivisional1: 'Cincinnati Bengals',
    afcDivisional2: 'Buffalo Bills',
    afcChampions: 'Cincinnati Bengals',
    nfcWildCard1: 'Tampa Bay Buccaneers',
    nfcWildCard2: 'Dallas Cowboys',
    nfcWildCard3: 'Los Angeles Rams',
    nfcDivisional1: 'Green Bay Packers',
    nfcDivisional2: 'Tampa Bay Buccaneers',
    nfcChampions: 'Tampa Bay Buccaneers',
    superbowl: 'Tampa Bay Buccaneers',
    tiebreaker: '52',
    points: 0,
  },
  {
    'First Name': 'Yash',
    'Last Name': 'H',
    name: 'Yash H',
    id: 8152,
    afcWildCard1: 'Las Vegas Raiders',
    afcWildCard2: 'Buffalo Bills',
    afcWildCard3: 'Kansas City Chiefs',
    afcDivisional1: 'Tennessee Titans',
    afcDivisional2: 'Kansas City Chiefs',
    afcChampions: 'Kansas City Chiefs',
    nfcWildCard1: 'Tampa Bay Buccaneers',
    nfcWildCard2: 'Dallas Cowboys',
    nfcWildCard3: 'Arizona Cardinals',
    nfcDivisional1: 'Green Bay Packers',
    nfcDivisional2: 'Tampa Bay Buccaneers',
    nfcChampions: 'Green Bay Packers',
    superbowl: 'Green Bay Packers',
    tiebreaker: '64',
    points: 0,
  },
  {
    'First Name': 'Yunsik',
    'Last Name': '',
    name: 'Yunsik ',
    id: 4724,
    afcWildCard1: 'Cincinnati Bengals',
    afcWildCard2: 'Buffalo Bills',
    afcWildCard3: 'Kansas City Chiefs',
    afcDivisional1: 'Cincinnati Bengals',
    afcDivisional2: 'Kansas City Chiefs',
    afcChampions: 'Kansas City Chiefs',
    nfcWildCard1: 'Tampa Bay Buccaneers',
    nfcWildCard2: 'San Francisco 49ers',
    nfcWildCard3: 'Los Angeles Rams',
    nfcDivisional1: 'Green Bay Packers',
    nfcDivisional2: 'Los Angeles Rams',
    nfcChampions: 'Los Angeles Rams',
    superbowl: 'Los Angeles Rams',
    tiebreaker: '66',
    points: 0,
  },
  {
    'First Name': 'Zeeshon',
    'Last Name': '',
    name: 'Zeeshon ',
    id: 9303,
    afcWildCard1: 'Cincinnati Bengals',
    afcWildCard2: 'Buffalo Bills',
    afcWildCard3: 'Kansas City Chiefs',
    afcDivisional1: 'Cincinnati Bengals',
    afcDivisional2: 'Kansas City Chiefs',
    afcChampions: 'Kansas City Chiefs',
    nfcWildCard1: 'Tampa Bay Buccaneers',
    nfcWildCard2: 'San Francisco 49ers',
    nfcWildCard3: 'Arizona Cardinals',
    nfcDivisional1: 'Green Bay Packers',
    nfcDivisional2: 'Tampa Bay Buccaneers',
    nfcChampions: 'Green Bay Packers',
    superbowl: 'Green Bay Packers',
    tiebreaker: '58',
    points: 0,
  },
  {
    'First Name': 'Eshaan',
    'Last Name': '',
    name: 'Eshaan ',
    id: 8372,
    afcWildCard1: 'Cincinnati Bengals',
    afcWildCard2: 'New England Patriots',
    afcWildCard3: 'Kansas City Chiefs',
    afcDivisional1: 'Tennessee Titans',
    afcDivisional2: 'Kansas City Chiefs',
    afcChampions: 'Kansas City Chiefs',
    nfcWildCard1: 'Tampa Bay Buccaneers',
    nfcWildCard2: 'San Francisco 49ers',
    nfcWildCard3: 'Los Angeles Rams',
    nfcDivisional1: 'Green Bay Packers',
    nfcDivisional2: 'Los Angeles Rams',
    nfcChampions: 'Green Bay Packers',
    superbowl: 'Green Bay Packers',
    tiebreaker: '54',
    points: 0,
  },
  {
    'First Name': 'Jaap',
    'Last Name': '',
    name: 'Jaap ',
    id: 1716,
    afcWildCard1: 'Cincinnati Bengals',
    afcWildCard2: 'Buffalo Bills',
    afcWildCard3: 'Kansas City Chiefs',
    afcDivisional1: 'Tennessee Titans',
    afcDivisional2: 'Kansas City Chiefs',
    afcChampions: 'Kansas City Chiefs',
    nfcWildCard1: 'Tampa Bay Buccaneers',
    nfcWildCard2: 'Dallas Cowboys',
    nfcWildCard3: 'Arizona Cardinals',
    nfcDivisional1: 'Green Bay Packers',
    nfcDivisional2: 'Tampa Bay Buccaneers',
    nfcChampions: 'Green Bay Packers',
    superbowl: 'Green Bay Packers',
    tiebreaker: '50',
    points: 0,
  },
  {
    'First Name': 'Akshay C',
    'Last Name': '',
    name: 'Akshay C ',
    id: 1372,
    afcWildCard1: 'Cincinnati Bengals',
    afcWildCard2: 'New England Patriots',
    afcWildCard3: 'Kansas City Chiefs',
    afcDivisional1: 'New England Patriots',
    afcDivisional2: 'Kansas City Chiefs',
    afcChampions: 'Kansas City Chiefs',
    nfcWildCard1: 'Tampa Bay Buccaneers',
    nfcWildCard2: 'Dallas Cowboys',
    nfcWildCard3: 'Arizona Cardinals',
    nfcDivisional1: 'Green Bay Packers',
    nfcDivisional2: 'Tampa Bay Buccaneers',
    nfcChampions: 'Tampa Bay Buccaneers',
    superbowl: 'Tampa Bay Buccaneers',
    tiebreaker: '44',
    points: 0,
  },
  {
    'First Name': 'Shanky',
    'Last Name': '',
    name: 'Shanky ',
    id: 8394,
    afcWildCard1: 'Las Vegas Raiders',
    afcWildCard2: 'New England Patriots',
    afcWildCard3: 'Kansas City Chiefs',
    afcDivisional1: 'Tennessee Titans',
    afcDivisional2: 'Kansas City Chiefs',
    afcChampions: 'Tennessee Titans',
    nfcWildCard1: 'Tampa Bay Buccaneers',
    nfcWildCard2: 'San Francisco 49ers',
    nfcWildCard3: 'Los Angeles Rams',
    nfcDivisional1: 'Green Bay Packers',
    nfcDivisional2: 'Tampa Bay Buccaneers',
    nfcChampions: 'Green Bay Packers',
    superbowl: 'Green Bay Packers',
    tiebreaker: '52',
    points: 0,
  },
  {
    'First Name': 'Abi S',
    'Last Name': '',
    name: 'Abi S ',
    id: 4165,
    afcWildCard1: 'Cincinnati Bengals',
    afcWildCard2: 'New England Patriots',
    afcWildCard3: 'Pittsburgh Steelers',
    afcDivisional1: 'Pittsburgh Steelers',
    afcDivisional2: 'Cincinnati Bengals',
    afcChampions: 'Pittsburgh Steelers',
    nfcWildCard1: 'Philadelphia Eagles',
    nfcWildCard2: 'Dallas Cowboys',
    nfcWildCard3: 'Los Angeles Rams',
    nfcDivisional1: 'Green Bay Packers',
    nfcDivisional2: 'Los Angeles Rams',
    nfcChampions: 'Los Angeles Rams',
    superbowl: 'Pittsburgh Steelers',
    tiebreaker: '36',
    points: 0,
  },
  {
    'First Name': 'Neha',
    'Last Name': '',
    name: 'Neha ',
    id: 4379,
    afcWildCard1: 'Cincinnati Bengals',
    afcWildCard2: 'Buffalo Bills',
    afcWildCard3: 'Kansas City Chiefs',
    afcDivisional1: 'Tennessee Titans',
    afcDivisional2: 'Kansas City Chiefs',
    afcChampions: 'Kansas City Chiefs',
    nfcWildCard1: 'Tampa Bay Buccaneers',
    nfcWildCard2: 'Dallas Cowboys',
    nfcWildCard3: 'Arizona Cardinals',
    nfcDivisional1: 'Green Bay Packers',
    nfcDivisional2: 'Dallas Cowboys',
    nfcChampions: 'Green Bay Packers',
    superbowl: 'Green Bay Packers',
    tiebreaker: '43',
    points: 0,
  },
  {
    'First Name': 'Sidd A',
    'Last Name': '',
    name: 'Sidd A ',
    id: 4816,
    afcWildCard1: 'Cincinnati Bengals',
    afcWildCard2: 'Buffalo Bills',
    afcWildCard3: 'Pittsburgh Steelers',
    afcDivisional1: 'Tennessee Titans',
    afcDivisional2: 'Cincinnati Bengals',
    afcChampions: 'Cincinnati Bengals',
    nfcWildCard1: 'Tampa Bay Buccaneers',
    nfcWildCard2: 'Dallas Cowboys',
    nfcWildCard3: 'Los Angeles Rams',
    nfcDivisional1: 'Green Bay Packers',
    nfcDivisional2: 'Dallas Cowboys',
    nfcChampions: 'Dallas Cowboys',
    superbowl: 'Dallas Cowboys',
    tiebreaker: '45',
    points: 0,
  },
  {
    'First Name': 'Jake Berch',
    'Last Name': '',
    name: 'Jake Berch ',
    id: 2970,
    afcWildCard1: 'Las Vegas Raiders',
    afcWildCard2: 'New England Patriots',
    afcWildCard3: 'Kansas City Chiefs',
    afcDivisional1: 'Tennessee Titans',
    afcDivisional2: 'Kansas City Chiefs',
    afcChampions: 'Kansas City Chiefs',
    nfcWildCard1: 'Tampa Bay Buccaneers',
    nfcWildCard2: 'San Francisco 49ers',
    nfcWildCard3: 'Los Angeles Rams',
    nfcDivisional1: 'Green Bay Packers',
    nfcDivisional2: 'Los Angeles Rams',
    nfcChampions: 'Los Angeles Rams',
    superbowl: 'Los Angeles Rams',
    tiebreaker: '55',
    points: 0,
  },
  {
    'First Name': 'TK',
    'Last Name': '',
    name: 'TK ',
    id: 2414,
    afcWildCard1: 'Cincinnati Bengals',
    afcWildCard2: 'Buffalo Bills',
    afcWildCard3: 'Kansas City Chiefs',
    afcDivisional1: 'Cincinnati Bengals',
    afcDivisional2: 'Kansas City Chiefs',
    afcChampions: 'Kansas City Chiefs',
    nfcWildCard1: 'Tampa Bay Buccaneers',
    nfcWildCard2: 'San Francisco 49ers',
    nfcWildCard3: 'Los Angeles Rams',
    nfcDivisional1: 'Green Bay Packers',
    nfcDivisional2: 'Los Angeles Rams',
    nfcChampions: 'Los Angeles Rams',
    superbowl: 'Kansas City Chiefs',
    tiebreaker: '62',
    points: 0,
  },
  {
    'First Name': 'Kayal & Nila',
    'Last Name': '',
    name: 'Kayal & Nila ',
    id: 9476,
    afcWildCard1: 'Cincinnati Bengals',
    afcWildCard2: 'Buffalo Bills',
    afcWildCard3: 'Kansas City Chiefs',
    afcDivisional1: 'Tennessee Titans',
    afcDivisional2: 'Kansas City Chiefs',
    afcChampions: 'Kansas City Chiefs',
    nfcWildCard1: 'Tampa Bay Buccaneers',
    nfcWildCard2: 'San Francisco 49ers',
    nfcWildCard3: 'Los Angeles Rams',
    nfcDivisional1: 'Green Bay Packers',
    nfcDivisional2: 'Tampa Bay Buccaneers',
    nfcChampions: 'Green Bay Packers',
    superbowl: 'Green Bay Packers',
    tiebreaker: '45',
    points: 0,
  },
  {
    'First Name': 'Kavin',
    'Last Name': '',
    name: 'Kavin ',
    id: 5489,
    afcWildCard1: 'Las Vegas Raiders',
    afcWildCard2: 'Buffalo Bills',
    afcWildCard3: 'Kansas City Chiefs',
    afcDivisional1: 'Tennessee Titans',
    afcDivisional2: 'Kansas City Chiefs',
    afcChampions: 'Tennessee Titans',
    nfcWildCard1: 'Tampa Bay Buccaneers',
    nfcWildCard2: 'Dallas Cowboys',
    nfcWildCard3: 'Arizona Cardinals',
    nfcDivisional1: 'Green Bay Packers',
    nfcDivisional2: 'Tampa Bay Buccaneers',
    nfcChampions: 'Green Bay Packers',
    superbowl: 'Tennessee Titans',
    tiebreaker: '50',
    points: 0,
  },
  {
    'First Name': 'Logan C',
    'Last Name': '',
    name: 'Logan C ',
    id: 9093,
    afcWildCard1: 'Cincinnati Bengals',
    afcWildCard2: 'Buffalo Bills',
    afcWildCard3: 'Kansas City Chiefs',
    afcDivisional1: 'Cincinnati Bengals',
    afcDivisional2: 'Buffalo Bills',
    afcChampions: 'Cincinnati Bengals',
    nfcWildCard1: 'Tampa Bay Buccaneers',
    nfcWildCard2: 'San Francisco 49ers',
    nfcWildCard3: 'Los Angeles Rams',
    nfcDivisional1: 'Green Bay Packers',
    nfcDivisional2: 'Tampa Bay Buccaneers',
    nfcChampions: 'Tampa Bay Buccaneers',
    superbowl: 'Tampa Bay Buccaneers',
    tiebreaker: '47',
    points: 0,
  },
  {
    'First Name': 'Surya',
    'Last Name': '',
    name: 'Surya ',
    id: 9886,
    afcWildCard1: 'Cincinnati Bengals',
    afcWildCard2: 'Buffalo Bills',
    afcWildCard3: 'Kansas City Chiefs',
    afcDivisional1: 'Tennessee Titans',
    afcDivisional2: 'Kansas City Chiefs',
    afcChampions: 'Kansas City Chiefs',
    nfcWildCard1: 'Tampa Bay Buccaneers',
    nfcWildCard2: 'Dallas Cowboys',
    nfcWildCard3: 'Los Angeles Rams',
    nfcDivisional1: 'Green Bay Packers',
    nfcDivisional2: 'Dallas Cowboys',
    nfcChampions: 'Green Bay Packers',
    superbowl: 'Green Bay Packers',
    tiebreaker: '67',
    points: 0,
  },
  {
    'First Name': 'Andrew',
    'Last Name': '',
    name: 'Andrew ',
    id: 9039,
    afcWildCard1: 'Cincinnati Bengals',
    afcWildCard2: 'Buffalo Bills',
    afcWildCard3: 'Kansas City Chiefs',
    afcDivisional1: 'Tennessee Titans',
    afcDivisional2: 'Kansas City Chiefs',
    afcChampions: 'Kansas City Chiefs',
    nfcWildCard1: 'Tampa Bay Buccaneers',
    nfcWildCard2: 'San Francisco 49ers',
    nfcWildCard3: 'Los Angeles Rams',
    nfcDivisional1: 'Green Bay Packers',
    nfcDivisional2: 'Tampa Bay Buccaneers',
    nfcChampions: 'Green Bay Packers',
    superbowl: 'Kansas City Chiefs',
    tiebreaker: '51',
    points: 0,
  },
];

export default data;
